package ca.ott.al.starmap.exception;

public class InvalidParameterValueException extends Exception {
    /**
     * Generated by eclipse
     */
    private static final long serialVersionUID = 4476890168582738675L;

    public InvalidParameterValueException(String message){
        super(message);
    }
}
